# Generated by Django 5.1 on 2024-09-02 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('model', models.CharField(max_length=100, verbose_name='Модель продукта')),
                ('release_date', models.DateField(verbose_name='Дата выхода на рынок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ElectronicsChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название звена')),
                ('node_type', models.CharField(choices=[('factory', 'Завод'), ('retail', 'Розничная сеть'), ('entrepreneur', 'Индивидуальный предприниматель')], max_length=20, verbose_name='Тип звена')),
                ('email', models.EmailField(max_length=254, verbose_name='Email для связи')),
                ('country', models.CharField(max_length=100, verbose_name='Страна расположения')),
                ('city', models.CharField(max_length=100, verbose_name='Город расположения')),
                ('street', models.CharField(max_length=100, verbose_name='Улица расположения')),
                ('house_number', models.CharField(max_length=20, verbose_name='Номер дома')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Задолженность перед поставщиком')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='chain.electronicschain', verbose_name='Поставщик')),
                ('products', models.ManyToManyField(related_name='electronics_chains', to='chain.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Звено сети электроники',
                'verbose_name_plural': 'Звенья сети электроники',
            },
        ),
    ]
