# Generated by Django 5.1 on 2024-09-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicschain',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город расположения'),
        ),
        migrations.AlterField(
            model_name='electronicschain',
            name='debt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Задолженность перед поставщиком'),
        ),
        migrations.AlterField(
            model_name='electronicschain',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email для связи'),
        ),
        migrations.AlterField(
            model_name='electronicschain',
            name='house_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='electronicschain',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='electronics_chains', to='chain.product', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='electronicschain',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица расположения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выхода на рынок'),
        ),
    ]
