# Generated by Django 5.1 on 2024-09-02 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0002_alter_electronicschain_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronicschain',
            name='owner',
        ),
    ]
